name: Ilk pipeline

#trigger (tetikleyici)
on:
  push: 
    branches: [ "main" ]

jobs:
  docker-login:
    name: Login to docker
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3

 #docker hub login
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
